# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mGRyGGLybHbOD_UfxvYye2dBjK8veCML
"""

from google.colab import ai

# Initialize variables
name = input("What do you want to be called? ")

# Memory storage
memory = []

# Personalized sentences baked in
eq = (f"Generate 1 nice sentence that runs along the lines of 'if you ever need help, just confide in me.' "
      f"and it needs to include {name}: which is the person's name and I don't want the why it works part. Just give me the sentence")

rq = (f"Generate 1 nice convo starter that runs along the lines of 'what's on your mind' "
      f"and it needs to include {name}: the person's name and needs to be chill. and I don't want the why it works part. Just give me the sentence")

# First greeting
print(f"Mark AI: Hello! I'm Mark. How can I help you today, {name}?")

# Convo starter
Prompt = ai.generate_text(rq)
Question = input(f"{Prompt} : ")
memory.append(f"{name}: {Question}")

print(f"Sorry, I didn't get that, {name}. Could you type it twice here?")

# Main loop
while True:
    Question = input(f"{name}, type anything here and I'll help you with it: ")

    if Question.lower() == "quit":
        print(f"Mark AI: Bye, see you next time, {name}!")
        break

    # Combine previous memory to give context
    context = "\n".join(memory)
    prompt_with_context = f"{context}\n{name}: {Question}\nMark AI:"

    # Generate AI response
    response = ai.generate_text(prompt_with_context).strip()
    print(f"Mark AI: {response}")

    # Save to memory
    memory.append(f"{name}: {Question}")
    memory.append(f"Mark AI: {response}")

    # Repeat helper sentence after each response
    helper = ai.generate_text(eq).strip()
    print(helper)